version: '3.8'

services:

  sync_api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/project
    environment: 
      PYTHONPATH: /project/src:$PYTHONPATH      
    command: ./entrypoints/sync_api.sh
    depends_on:
      - postgres
    tty: true
    stdin_open: true

  async_api:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/project
    environment: 
      PYTHONPATH: /project/src:$PYTHONPATH      
    command: ./entrypoints/async_api.sh
    depends_on:
      - postgres
    tty: true
    stdin_open: true    

  print_tasks:
    build: .
    volumes:
      - .:/project 
    environment:
      PYTHONPATH: /project/src:$PYTHONPATH
    command: ./entrypoints/print_tasks.sh
    depends_on:
     - postgres
    tty: true
    stdin_open: true

  run_tests:
    build: .
    volumes:
      - .:/project
    environment: 
      PYTHONPATH: /project/src:$PYTHONPATH
    command: pytest
    depends_on:
      - postgres
    tty: true
    stdin_open: true  

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db